import java.util.Date;


public class ProjectDetailsReloader extends DataReloader {

    protected ProjectDetailsReloader(Project project, PeriodicReloadPolicy reloadPolicy) {
        super(project, reloadPolicy);
    }

    @Override
    protected void loadData() {
        System.out.println("Loading project details for project " + project.getName());
        System.out.println("(Talking to database and updating our project-related objects.)");
        //this could be a lot of lines of code and involve collaborators, helpers, etc
        //...
        //...
        //...
        //...
        //...
        //...
        //...
        //... Talk to database,
        //... Build domain objects,
        //... Update stuff
        //...
        //...
        //...
        //...
        //...
        //... Clear previously cached data
        //...
        //... Cache fresh data
        project.setProjectDetails("Project details created: " + new Date(System.currentTimeMillis()));
    }

}
